apiVersion: v1
kind: ConfigMap
metadata:
  name: dbmap-init
  labels:
    app: postgresdb
data:
  db1.sql: |
    CREATE DATABASE xenonstack;
    \c xenonstack
    CREATE TABLE demo1(ID int not null primary key, NAME text not null, CITY text);

  db2.sql: |
    CREATE DATABASE vehicles;
    \c vehicles
    CREATE TABLE cars(ID int not null primary key, NAME text not null, PRICE int);

  db3.sql: |
    CREATE DATABASE company;
    \c company
    CREATE TABLE emp(ID int not null primary key, NAME text not null, SALARY int);

