apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresdb
spec:
  serviceName: my-service
  replicas: 1
  selector:
    matchLabels:
      app: postgresdb
  template:
    metadata:
      labels:
        app: postgresdb
    spec:
      containers:
        - name: postgresdb
          image: postgres:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: db-vol
              mountPath: /var/lib/postgres/data
            - name: init-scripts
              mountPath: /docker-entrypoint-initdb.d
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            - name: POSTGRES_USER
              value: sahil
            - name: POSTGRES_PASSWORD
              value: Sahil@123
            - name: PGPASSWORD
              value: Sahil@123
      volumes:
        - name: init-scripts
          configMap: 
            name: dbmap-init
  volumeClaimTemplates:
    - metadata:
        name: db-vol
      spec:
        accessModes: [ "ReadWriteOnce"]
        storageClassName: standard
        resources:
          requests:
            storage: 800Mi
# stateset from branch-1
