apiVersion: v1
kind: Pod
metadata:
  name: fetch-db-pod
spec:
  volumes:
    - name: db-dump
      persistentVolumeClaim:
        claimName: db-pvc
  containers:
    - name: fetch-db
      image: postgres:latest
      command: ["/bin/bash"]
      args:
        - "-c"
        - |
          while true; do
            echo "Fetching database..."
            PGPASSWORD=Sahil@123 pg_dump -h postgresdb.default.svc.cluster.local -U sahil demodb > /mnt/database.sql
            sleep 60
          done 
      volumeMounts:
        - name: db-dump
          mountPath: /mnt
