apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
  labels:
    type: local
spec:
  storageClassName: my-sg-class
  capacity:
    storage: 700Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/postgres"
